Add option for custom src directories
You can now add custom `src-<name>` directories that can be extracted via the `install` file using the `anms_install` function.

diff --git a/src/anms b/src/anms
--- a/src/anms
+++ b/src/anms
@@ -6,6 +6,7 @@
 
 export ANMS_HOME
 export ANMS_META
+export ANMS_LIB_FILE="/tmp/anms.lib.sh"
 
 declare self="$(readlink -f "$0")"
 declare address="$1"
@@ -152,7 +153,7 @@ pkg_install() {
     ANMS_HOME="$home/$mod"
     ANMS_META="$ANMS_HOME/META"
     
-    if yml_cmp %s_file_md5 "$hash" "$mod"; then
+    if yml_cmp %s_file_md5 "$hash" "$mod"; then    
         if [ ! -d "$ANMS_HOME" ]; then
             mkdir "$ANMS_HOME"
         
@@ -162,6 +163,7 @@ pkg_install() {
             fi
             
             cp "$ANMS_HOME/files.lst" "$ANMS_HOME/files.old.lst"
+            echo "" > "$ANMS_HOME/files.lst"
             arg=update
         fi
         
@@ -253,6 +255,51 @@ pkg_install() {
         done
         
         echo -e "\tRunning install script"
+        cat << EOF | tee $ANMS_LIB_FILE >/dev/null
+            anms_install() {
+                local arg i x
+            
+                case "\$1" in
+                    "src")
+                        echo -e "\tExtracting source files from src-\$2"
+                        while read file; do
+                            if grep -qe '/$' <<< "\$file"; then
+                                if [ ! -d "/\$file" ]; then
+                                    mkdir "/\$file"
+                                fi
+                            
+                            else
+                                tar -xf $archive "src-\$2/\$file" -O > "/\$file" 2> >(grep -v 'Removing lead' >&2)
+                            fi
+                            
+                        done < <(tar -tf $archive 2>/dev/null | grep -ve "^src-\$2/$" | grep -e "^src-\$2/" | sed "s/^src-\$2\///" | tee -a "$ANMS_HOME/files.lst")
+                    ;;
+                    
+                    "ref")
+                        echo -e "\tAdding a file reference for '\$2'"
+                    
+                        if [ -e "\$2" ]; then 
+                            arg="\$(realpath --no-symlinks "\$2")"
+                            arg="\${arg:1}"
+                            i=\$(awk -F/ '{print NF-1}' <<< "\$arg")
+                            
+                            for ((x=1; x <= i; x++)); do
+                                echo "\$(cut -d '/' -f "-\$x" <<< "\$arg")/" >> "$ANMS_HOME/files.lst"
+                            done
+                            
+                            if [[ -d "\$2" && ! -L "\$2" ]]; then
+                                echo "\$arg/" >> "$ANMS_HOME/files.lst"
+                                
+                            else
+                                echo "\$arg" >> "$ANMS_HOME/files.lst"
+                            fi
+                        else
+                            echo "Failed to add reference. The path '\$2' does not exist."
+                        fi
+                    ;;
+                esac
+            }
+EOF
         if tar -tf $archive 2>/dev/null | grep -qe '^install\b'; then
             if ! tar -xf $archive 'install' -O 2> >(grep -v 'Removing lead' >&2) | bash -s -- $arg > >(sed 's/\(.*\)/\t\1/') 2> >(sed 's/\(.*\)/\t\1/' >&2); then
                 echo -e "\tThe install script failed to run properly" >&2
@@ -267,7 +314,11 @@ pkg_install() {
 		        tar -xf $archive "$scr" -O > "$ANMS_HOME/$scr" 2> >(grep -v 'Removing lead' >&2)
 		    fi
 		done
+		
+		awk '!seen[$0]++' $ANMS_HOME/files.lst > $ANMS_HOME/files.lst.tmp
+		mv $ANMS_HOME/files.lst.tmp $ANMS_HOME/files.lst
 
+        rm $ANMS_LIB_FILE 2>/dev/null
         rm "$ANMS_HOME/files.old.lst" 2>/dev/null
         rm "$ANMS_HOME/meta-files.old.lst" 2>/dev/null
         rm $archive 2>/dev/null
